name: Auto Hunt by @prakashchand72
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOMAIN: 'upstox.com'

jobs:
  subdomains:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 
    
    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        sudo apt-get install jq -y 
      shell: bash

    - name: Run Subfinder
      run: |
        subfinder -d $DOMAIN -o subfinder_output.txt
      shell: bash
    - name: Run crt.sh
      run: |
        curl -s "https://crt.sh/?q=%25.$DOMAIN&output=json" | jq -r '.[].name_value' | sed 's/\*\.//g' | sort -u | tee -a crt.txt
      shell: bash
    
    - name: Sort Sub-domains
      run: |
        cat subfinder_output.txt crt.txt | grep -v www | uniq -u | tee -a sorted_domains.txt
      shell: bash
   
    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: Subdomains results
        path: |
          subfinder_output.txt
          crt.txt
          sorted_domains.txt
  HTTPX:
    runs-on: ubuntu-latest
    needs: subdomains
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: Subdomains results
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 

    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest 
      shell: bash

    - name: HTTPX_Detailed 
      run: |
        cat sorted_domains.txt | httpx -sc -title -server | tee -a detailed_httpx.txt
      shell: bash
    - name: HTTPX_Live for endpoint
      run: | 
        cat sorted_domains.txt | httpx -mc 200 | tee -a 200httpx.txt
      shell: bash
    - name: httpx for all - no filtering
      run: |
        cat sorted_domains.txt | httpx | tee -a normalhttpx.txt
      shell: bash 

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: HTTPX results
        path: |
          detailed_httpx.txt
          200httpx.txt
          normalhttpx.txt

  EndPonts-Waybackurls:
    runs-on: ubuntu-latest
    needs: HTTPX
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: HTTPX results
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 

    - name: Install Required Tools 
      run: |
        go install github.com/tomnomnom/waybackurls@latest
      shell: bash

    - name: Gathering Endpoints 
      run: |
        cat 200httpx.txt | waybackurls > waybackurls.txt
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: endpoints results
        path: |
          waybackurls.txt

  Nuclei-VulnScanner:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 

    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
      shell: bash

    - name: Vulnarability Scanning  
      run: |
        nuclei -l waybackurls.txt -es info > nuclei_output.txt
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: nuclei_output results
        path: |
          nuclei_output.txt

  Secret-Finder:
    runs-on: ubuntu-latest
    needs: EndPonts-Waybackurls
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: endpoints results

    - name: Install Required Tools 
      run: |
        sudo apt-get -y install python3 python3-pip
        sudo pip3 install requests argparse dnspython
        git clone https://github.com/m4ll0k/SecretFinder ~/SecretFinder
        echo "installing additional dependency of SecretFinder"
        pip3 install -r ~/SecretFinder/requirements.txt
      shell: bash

    - name: Secret Finder by analyzing js file   
      run: |
        cat waybackurls.txt | grep js > endpoints_with_js.txt
        cat endpoints_with_js.txt | while read js ; do python3 ~/SecretFinder/SecretFinder.py -i $js -o cli > secretfinder.txt
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: secret-finder results
        path: |
          secretfinder.txt
        

